import { getSupabase } from "./supabase.ts";

/**
 * An office record from the public.offices table.
 *
 * Office IDs are opaque UUIDs generated by Postgres (gen_random_uuid()).
 * They are NOT guessable, which eliminates enumeration attacks against the
 * Realtime channel namespace (carry:{officeId}:{code}).  NFC tags must be
 * re-provisioned via ProvisionTag if office IDs change.
 *
 * See supabase/migrations/20250101000002_offices.sql for the table definition
 * and RLS policies.
 */
export interface Office {
  id: string;
  name: string;
}

/**
 * Fetches a single office by its opaque UUID.
 * Returns null if the office does not exist or is inaccessible.
 *
 * Used by PatientView (to display the clinic name) and DeskView (alongside
 * the membership check).
 */
export async function fetchOffice(id: string): Promise<Office | null> {
  const { data, error } = await getSupabase()
    .from("offices")
    .select("id, name")
    .eq("id", id)
    .maybeSingle();

  if (error || !data) return null;
  return { id: data.id as string, name: data.name as string };
}

/**
 * Fetches all offices, ordered by name.
 *
 * ⚠️  Returns every row in public.offices (publicly readable per RLS).
 * Do NOT use this in the NFC provisioning tool — use fetchAuthorizedOffices
 * instead so a staff member can only write tags for offices they belong to.
 */
export async function fetchAllOffices(): Promise<Office[]> {
  const { data, error } = await getSupabase()
    .from("offices")
    .select("id, name")
    .order("name");

  if (error || !data) return [];
  return (data as { id: string; name: string }[]).map((r) => ({
    id: r.id,
    name: r.name,
  }));
}

/**
 * Fetches only the offices that `userId` is a member of, ordered by name.
 *
 * Uses a two-step query:
 *   1. office_staff WHERE user_id = userId  → list of office_ids
 *   2. offices WHERE id IN (office_ids)     → full office records
 *
 * Used by ProvisionTag so a staff member can only write NFC tags for offices
 * they are authorised to manage.  Returns an empty array if the user has no
 * memberships or if either query fails.
 */
export async function fetchAuthorizedOffices(userId: string): Promise<Office[]> {
  const { data: staffRows, error: staffError } = await getSupabase()
    .from("office_staff")
    .select("office_id")
    .eq("user_id", userId);

  if (staffError || !staffRows?.length) return [];

  const ids = staffRows.map((r) => r.office_id as string);

  const { data: officeRows, error: officeError } = await getSupabase()
    .from("offices")
    .select("id, name")
    .in("id", ids)
    .order("name");

  if (officeError || !officeRows) return [];
  return (officeRows as { id: string; name: string }[]).map((r) => ({
    id: r.id,
    name: r.name,
  }));
}
