import { useState } from "react";
import { AlertCircle, Zap } from "lucide-react";

interface Props {
  error?: string;
  onSubmit: (code: string) => void;
  onBack: () => void;
}

/**
 * Pairing codes are now 8 characters from an unambiguous alphabet
 * (no 0/O, no 1/I/l) generated by generatePairingCode() in transit.ts.
 * The desk displays the code as XXXX-XXXX; the patient types it without
 * the hyphen (the input strips everything that isn't in the alphabet).
 */
const VALID_CHAR_RE = /[^A-HJ-NP-Z2-9]/g;
const CODE_LENGTH = 8;

export function CodeEntry({ error, onSubmit, onBack }: Props) {
  const [code, setCode] = useState("");

  const handleChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    const normalized = e.target.value
      .toUpperCase()
      .replace(VALID_CHAR_RE, "")
      .slice(0, CODE_LENGTH);
    setCode(normalized);
  };

  // Auto-submit once all 8 characters are entered.
  const handleKeyDown = (e: React.KeyboardEvent<HTMLInputElement>) => {
    if (e.key === "Enter" && code.length === CODE_LENGTH) onSubmit(code);
  };

  return (
    <div className="lf-pad lf-scroll">
      <h3 className="lf-h-solo">Enter desk code</h3>
      <p className="lf-note">
        Enter the 8-character code shown on the front-desk screen (without the
        hyphen). Letters are uppercase; digits never include 0 or 1 to avoid
        visual confusion.
      </p>

      {error && (
        <div id="code-error" className="lf-field-error" role="alert">
          <AlertCircle size={14} aria-hidden="true" />
          {error}
        </div>
      )}

      <label className="lf-field">
        <span>Pairing code</span>
        <input
          type="text"
          inputMode="text"
          maxLength={CODE_LENGTH}
          value={code}
          onChange={handleChange}
          onKeyDown={handleKeyDown}
          placeholder="XXXXXXXX"
          autoFocus
          autoCapitalize="characters"
          autoCorrect="off"
          autoComplete="off"
          spellCheck={false}
          aria-invalid={error ? true : undefined}
          aria-describedby={error ? "code-error" : undefined}
          style={{
            fontFamily: "'IBM Plex Mono', monospace",
            letterSpacing: "0.35em",
            fontSize: "20px",
            textAlign: "center",
            textTransform: "uppercase",
          }}
        />
      </label>

      <p className="lf-note" style={{ marginTop: 6 }}>
        {code.length} / {CODE_LENGTH} characters
      </p>

      <div className="lf-actions">
        <button className="lf-secondary" onClick={onBack} type="button">Back</button>
        <button
          className="lf-primary lf-send"
          disabled={code.length !== CODE_LENGTH}
          onClick={() => onSubmit(code)}
          type="button"
        >
          <Zap size={15} /> Connect
        </button>
      </div>
    </div>
  );
}
