-- Migration: offices table
--
-- Replaces the hard-coded office list previously bundled in src/lib/offices.ts.
-- Office IDs are opaque UUIDs generated by Postgres, making them non-guessable
-- and eliminating enumeration attacks against the Realtime channel namespace
-- (carry:{officeId}:{code}).
--
-- ⚠️  NFC TAG MIGRATION
-- Any NFC tags provisioned with the old short IDs ("demo", "north", "harbor")
-- must be re-written via ProvisionTag after seeding the offices table, because
-- the URL format /o/{officeId} now expects a UUID.
--
-- Adding an office:
--   INSERT INTO public.offices (name) VALUES ('Northside Family Practice');
--   -- Copy the generated `id` UUID into ProvisionTag to write the NFC tag.
--
-- The generated UUID is the only credential that routes a patient to a desk,
-- so treat tag URLs as moderately sensitive (obscurity + encryption, not public).

create table if not exists public.offices (
  id         uuid        primary key default gen_random_uuid(),
  name       text        not null,
  created_at timestamptz not null default now()
);

alter table public.offices enable row level security;

-- Patients and staff both need to read office names: patients see the clinic
-- name on their welcome screen; staff need it for the membership check.
create policy "offices are publicly readable"
  on public.offices
  for select
  to anon, authenticated
  using (true);

-- All mutations are reserved for the service role (Supabase dashboard or
-- admin scripts only — no client-side writes are permitted).
create policy "service role manages offices"
  on public.offices
  for all
  to service_role
  using (true)
  with check (true);

-- Speeds up single-row lookups by PatientView / DeskView.
create index if not exists offices_id_idx on public.offices (id);

-- Add a foreign-key reference from office_staff so that removing an office
-- automatically removes all its staff rows (prevents stale membership).
-- Note: office_staff.office_id is typed as TEXT; Postgres allows a FK from
-- TEXT to UUID via an implicit cast only if the text column uses ::uuid.
-- The safer approach is to store the UUID as TEXT in office_staff and validate
-- it via the RLS policy join rather than a native FK constraint.
-- If you prefer a native FK, run:
--   ALTER TABLE public.office_staff
--     ALTER COLUMN office_id TYPE uuid USING office_id::uuid;
--   ALTER TABLE public.office_staff
--     ADD CONSTRAINT office_staff_office_fk
--     FOREIGN KEY (office_id) REFERENCES public.offices (id) ON DELETE CASCADE;
-- This requires that all existing office_staff rows already hold valid UUIDs.
